"""Generate a Markdown (and optionally PDF) report for a PUMA run."""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def generate_report(
    run_id: str,
    db_path: Path | str = "data/puma.db",
    results_root: Path | str = "results",
    to_pdf: bool = False,
) -> Path:
    """Generate results/<run_id>/report.md and return its path."""
    from puma.dashboard.data import load_metrics, load_predictions, load_runs

    db_path = Path(db_path)
    results_root = Path(results_root)
    run_dir = results_root / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    runs_df = load_runs(db_path)
    run_row = runs_df[runs_df["run_id"] == run_id]
    if run_row.empty:
        raise ValueError(f"Run '{run_id}' not found in {db_path}")

    run = run_row.iloc[0].to_dict()
    metrics_df = load_metrics(db_path, run_ids=[run_id])
    preds_df = load_predictions(db_path, run_id=run_id)

    metrics: dict[str, Any] = {
        r["metric_name"]: r["value"] for _, r in metrics_df.iterrows()
    }

    lines: list[str] = []

    # Header
    lines += [
        f"# PUMA Run Report: `{run_id}`",
        "",
        f"Generated: {datetime.now(UTC).isoformat(timespec='seconds')}",
        "",
    ]

    # Executive summary
    lines += [
        "## Executive Summary",
        "",
    ]
    status = run.get("status", "unknown")
    started = run.get("started_at", "n/a")
    finished = run.get("finished_at", "n/a")
    profile = run.get("profile", "n/a")

    try:
        spec_yaml = json.loads(run.get("spec_yaml", "{}"))
    except Exception:
        spec_yaml = {}

    scenario = spec_yaml.get("scenario", "n/a")
    models = spec_yaml.get("models", [])
    sample_size = spec_yaml.get("sample_size", "n/a")
    strategies = spec_yaml.get("adaptation", {}).get("strategy", [])

    lines += [
        "| Field | Value |",
        "|-------|-------|",
        f"| Run ID | `{run_id}` |",
        f"| Scenario | {scenario} |",
        f"| Status | {status} |",
        f"| Profile | {profile} |",
        f"| Models | {', '.join(models) if models else 'n/a'} |",
        f"| Strategies | {', '.join(strategies) if strategies else 'n/a'} |",
        f"| Sample size | {sample_size} |",
        f"| Started | {started} |",
        f"| Finished | {finished} |",
        f"| Total predictions | {len(preds_df)} |",
        "",
    ]

    # Metrics table
    lines += [
        "## Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    for metric_name, value in sorted(metrics.items()):
        if isinstance(value, float):
            lines.append(f"| {metric_name} | {value:.4f} |")
        else:
            lines.append(f"| {metric_name} | {value} |")
    lines.append("")

    # Per-model breakdown if multiple models
    if not preds_df.empty and "model" in preds_df.columns and len(preds_df["model"].unique()) > 1:
        lines += [
            "## Per-Model Breakdown",
            "",
            "| Model | Predictions | Parse failures |",
            "|-------|-------------|----------------|",
        ]
        for model, grp in preds_df.groupby("model"):
            n_preds = len(grp)
            n_fail = grp["parsed_label"].isna().sum()
            lines.append(f"| {model} | {n_preds} | {n_fail} |")
        lines.append("")

    # Perturbations section
    if not preds_df.empty and "perturbation" in preds_df.columns:
        perturbed = preds_df[preds_df["perturbation"].notna()]
        if not perturbed.empty:
            lines += [
                "## Robustness (Perturbations)",
                "",
                "| Perturbation | Predictions |",
                "|--------------|-------------|",
            ]
            for pert, grp in perturbed.groupby("perturbation"):
                lines.append(f"| {pert} | {len(grp)} |")
            lines.append("")

    # Emissions section
    _append_emissions_section(lines, run_dir)

    # Latency
    if "latency.p50" in metrics or "latency.p95" in metrics:
        lines += [
            "## Latency",
            "",
            "| Percentile | ms |",
            "|------------|-----|",
        ]
        for key in ("latency.p50", "latency.p95", "latency.p99", "latency.mean"):
            if key in metrics:
                lines.append(f"| {key.split('.')[-1].upper()} | {metrics[key]:.1f} |")
        lines.append("")

    # Methodology note
    lines += [
        "## Methodology",
        "",
        "All inference runs executed locally via Ollama. "
        "No external API calls. Results are deterministic (seed fixed per run-spec).",
        "",
        "---",
        f"*Generated by PUMA v2.0.0-dev — {datetime.now(UTC).strftime('%Y-%m-%d')}*",
    ]

    report_md = run_dir / "report.md"
    report_md.write_text("\n".join(lines), encoding="utf-8")

    if to_pdf:
        _convert_to_pdf(report_md)

    return report_md


def _append_emissions_section(lines: list[str], run_dir: Path) -> None:
    emissions_csv = run_dir.parent.parent / "emissions.csv"
    if not emissions_csv.exists():
        return
    try:
        import pandas as pd

        df = pd.read_csv(emissions_csv)
        if df.empty:
            return
        latest = df.iloc[-1]
        lines += [
            "## Sustainability",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| CO₂ equivalent (kg) | {latest.get('emissions', 'n/a')} |",
            f"| Energy consumed (kWh) | {latest.get('energy_consumed', 'n/a')} |",
            f"| Duration (s) | {latest.get('duration', 'n/a')} |",
            "",
        ]
    except Exception:
        pass


def _convert_to_pdf(report_md: Path) -> None:
    pdf_path = report_md.with_suffix(".pdf")
    try:
        subprocess.run(
            ["pandoc", str(report_md), "-o", str(pdf_path), "--pdf-engine=xelatex"],
            check=True,
            capture_output=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass  # pandoc not installed — silently skip
