"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-10 00:53:21.172371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('gold_label', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('instance_id', name=op.f('pk_instances')),
    sa.UniqueConstraint('dataset', 'source_id', name='uq_dataset_source')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('spec_hash', sa.String(length=16), nullable=False),
    sa.Column('spec_yaml', sa.Text(), nullable=True),
    sa.Column('profile', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    op.create_table('emissions',
    sa.Column('emission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=True),
    sa.Column('co2_kg', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('cpu_energy', sa.Float(), nullable=True),
    sa.Column('gpu_energy', sa.Float(), nullable=True),
    sa.Column('ram_energy', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_emissions_run_id_runs')),
    sa.PrimaryKeyConstraint('emission_id', name=op.f('pk_emissions'))
    )
    op.create_table('metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('subgroup', sa.String(length=128), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_metrics_run_id_runs')),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('pk_metrics'))
    )
    op.create_table('predictions',
    sa.Column('pred_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('prompt_hash', sa.String(length=16), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_label', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('logprobs_json', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('perturbation', sa.String(length=64), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.instance_id'], name=op.f('fk_predictions_instance_id_instances')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_predictions_run_id_runs')),
    sa.PrimaryKeyConstraint('pred_id', name=op.f('pk_predictions'))
    )
    op.create_table('profile_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('cpu', sa.String(length=128), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('gpu', sa.String(length=128), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=True),
    sa.Column('ollama_version', sa.String(length=32), nullable=True),
    sa.Column('puma_version', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('fk_profile_snapshots_run_id_runs')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_profile_snapshots')),
    sa.UniqueConstraint('run_id', name=op.f('uq_profile_snapshots_run_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_snapshots')
    op.drop_table('predictions')
    op.drop_table('metrics')
    op.drop_table('emissions')
    op.drop_table('runs')
    op.drop_table('instances')
    # ### end Alembic commands ###
